# Generated by Django 2.2 on 2019-11-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191110_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mainimage',
            field=models.ImageField(blank=True, null=True, upload_to='media/products/'),
        ),
    ]
